import { DietPlan } from '../types';

export const defaultStarterDietPlans: DietPlan[] = [
  {
    id: 'diet_adv_shred_01',
    tenantId: 'tenant_default',
    title: 'ADV Competition Shred & Peak Conditioning',
    isAdv: true,
    category: 'ADV Competition Prep',
    targetGoal: 'Aggressive Fat Loss & Lean Muscle Hardening',
    dailyCalories: 2150,
    proteinGrams: 220,
    carbsGrams: 150,
    fatsGrams: 45,
    waterIntakeLiters: 4.5,
    description: 'Advanced pro-tier physique prep diet with timed carb refeeds, electrolyte monitoring, and high amino density.',
    supplements: [
      'Whey Protein Isolate (2 Scoops)',
      'Creatine Monohydrate (5g Post-Workout)',
      'BCAA / EAA Intra-Workout',
      'Multivitamin & Omega-3 Fish Oil',
      'L-Carnitine 3000mg Pre-Workout',
    ],
    dosAndDonts: {
      dos: [
        'Drink at least 4.5 Liters of pure water daily',
        'Weigh all food portions raw using a digital scale',
        'Keep pre and post-workout meal timing within 45 mins',
        'Perform 30-40 minutes of morning fasting cardio',
      ],
      donts: [
        'No refined sugars, sodas, or fruit juices',
        'Avoid extra salt or soy sauce after 7:00 PM',
        'No missed meals or skipping protein portions',
      ],
    },
    meals: [
      {
        id: 'm1',
        time: '07:30 AM',
        title: 'Meal 1 - Fasted Cardio Refuel',
        foodItems: ['6 Whole Egg Whites + 1 Whole Egg (Scrambled)', '60g Rolled Oats cooked in water with cinnamon', '10 Almonds'],
        calories: 380,
        proteinGrams: 35,
        carbsGrams: 40,
        fatsGrams: 10,
        notes: 'Take Multivitamin and Omega-3 with this meal.',
      },
      {
        id: 'm2',
        time: '11:00 AM',
        title: 'Meal 2 - Mid-Morning Macro Stack',
        foodItems: ['180g Grilled Chicken Breast', '120g Boiled White Rice or Sweet Potato', '1 Cup Steamed Broccoli & Cucumber'],
        calories: 420,
        proteinGrams: 48,
        carbsGrams: 35,
        fatsGrams: 6,
        notes: 'Lemon juice and herbs allowed for flavor.',
      },
      {
        id: 'm3',
        time: '02:30 PM',
        title: 'Meal 3 - Pre-Workout Energy Meal',
        foodItems: ['180g Lean Beef Mince / Chicken', '150g Boiled Brown Rice', 'Green Salad with Apple Cider Vinegar'],
        calories: 460,
        proteinGrams: 46,
        carbsGrams: 45,
        fatsGrams: 10,
        notes: 'Eat exactly 90 minutes before your workout session.',
      },
      {
        id: 'm4',
        time: '05:30 PM',
        title: 'Meal 4 - Intra/Post Workout Refuel',
        foodItems: ['1 Scoop Whey Isolate in water', '1 Medium Banana', '5g Creatine Monohydrate'],
        calories: 240,
        proteinGrams: 28,
        carbsGrams: 28,
        fatsGrams: 2,
        notes: 'Consume within 20 minutes post workout.',
      },
      {
        id: 'm5',
        time: '08:30 PM',
        title: 'Meal 5 - Anabolic Dinner & Bedtime Reset',
        foodItems: ['200g White Fish / Tilapia / Tuna fillet', 'Large Mixed Salad (Spinach, Cucumber, Asparagus)', '1 tbsp Olive Oil dressing'],
        calories: 380,
        proteinGrams: 45,
        carbsGrams: 12,
        fatsGrams: 15,
        notes: 'Low carb evening meal to maximize overnight growth hormone release.',
      },
    ],
  },
  {
    id: 'diet_adv_muscle_02',
    tenantId: 'tenant_default',
    title: 'ADV Hypertrophy & Maximum Muscle Density',
    isAdv: true,
    category: 'ADV Muscle Gain',
    targetGoal: 'Clean Muscle Hypertrophy & Strength Progression',
    dailyCalories: 2950,
    proteinGrams: 210,
    carbsGrams: 340,
    fatsGrams: 70,
    waterIntakeLiters: 4.0,
    description: 'Advanced muscle-building nutritional protocol engineered for maximum progressive overload recovery and metabolic health.',
    supplements: [
      'Whey Protein Concentrate/Isolate',
      'Creatine Monohydrate 5g Daily',
      'Mass Gainer / Oats Blend (Optional)',
      'ZMA (Zinc & Magnesium for Sleep & Testosterone)',
    ],
    dosAndDonts: {
      dos: [
        'Ensure steady progressive overload in gym workouts',
        'Sleep at least 7.5 to 8 hours every night',
        'Eat a high carb pre-workout meal for optimal glycogen pump',
      ],
      donts: [
        'Do not dirty bulk or consume excessive junk fast foods',
        'Do not skip leg day or post-workout protein intake',
      ],
    },
    meals: [
      {
        id: 'm1',
        time: '08:00 AM',
        title: 'Breakfast - Anabolic Power Oats',
        foodItems: ['100g Rolled Oats with Low Fat Milk', '2 Whole Eggs + 4 Egg Whites', '1 tbsp Peanut Butter', '1 Banana'],
        calories: 680,
        proteinGrams: 48,
        carbsGrams: 80,
        fatsGrams: 18,
      },
      {
        id: 'm2',
        time: '01:00 PM',
        title: 'Lunch - Clean Muscle Fuel',
        foodItems: ['220g Grilled Chicken Breast', '250g Steamed Basmati Rice', 'Steamed Vegetables with Olive Oil'],
        calories: 720,
        proteinGrams: 55,
        carbsGrams: 85,
        fatsGrams: 14,
      },
      {
        id: 'm3',
        time: '05:00 PM',
        title: 'Pre-Workout Snack',
        foodItems: ['2 Slices Whole Wheat Bread with Peanut Butter', '1 Scoop Whey Protein Shake', '1 Apple'],
        calories: 450,
        proteinGrams: 32,
        carbsGrams: 52,
        fatsGrams: 12,
      },
      {
        id: 'm4',
        time: '08:30 PM',
        title: 'Dinner - Heavy Recovery Feast',
        foodItems: ['200g Lean Beef / Red Meat / Chicken', '200g Boiled Potatoes or Rice', 'Fresh Green Salad'],
        calories: 650,
        proteinGrams: 52,
        carbsGrams: 65,
        fatsGrams: 16,
      },
    ],
  },
  {
    id: 'diet_adv_keto_03',
    tenantId: 'tenant_default',
    title: 'ADV Keto Pro Low-Carb Ketogenic Diet',
    isAdv: true,
    category: 'ADV Keto Pro',
    targetGoal: 'Ketosis Fat Oxidation & Insulin Sensitivity',
    dailyCalories: 1950,
    proteinGrams: 160,
    carbsGrams: 25,
    fatsGrams: 135,
    waterIntakeLiters: 4.0,
    description: 'Advanced ketogenic protocol for rapid body recomposition through targeted ketosis and healthy fat adaptation.',
    supplements: [
      'Electrolyte Powder (Sodium, Potassium, Magnesium)',
      'MCT Oil Powder',
      'Omega-3 Fish Oil Capsules',
    ],
    dosAndDonts: {
      dos: [
        'Maintain carbs strict under 25g net daily',
        'Add extra Himalayan pink salt to water for electrolytes',
        'Eat healthy avocados, olive oil, and grass-fed butter',
      ],
      donts: [
        'No cheat meals during first 3 weeks of keto adaptation',
        'Avoid hidden carbs in sauces, ketchups, or salad dressings',
      ],
    },
    meals: [
      {
        id: 'm1',
        time: '08:30 AM',
        title: 'Breakfast - Keto Omelette & MCT Coffee',
        foodItems: ['3 Whole Eggs Omelette cooked in Butter with Cheese', 'Black Coffee with 1 tsp MCT Oil', '1/2 Avocado'],
        calories: 550,
        proteinGrams: 30,
        carbsGrams: 5,
        fatsGrams: 45,
      },
      {
        id: 'm2',
        time: '01:30 PM',
        title: 'Lunch - High Fat Chicken Cobb Salad',
        foodItems: ['180g Chicken Thighs with Skin', 'Spinach & Lettuce', 'Olive Oil & Feta Cheese dressing'],
        calories: 620,
        proteinGrams: 45,
        carbsGrams: 8,
        fatsGrams: 44,
      },
      {
        id: 'm3',
        time: '07:30 PM',
        title: 'Dinner - Ribeye / Mutton & Green Veggies',
        foodItems: ['200g Beef Steak or Mutton Curry in Desi Ghee', 'Sautéed Asparagus & Garlic Spinach'],
        calories: 680,
        proteinGrams: 52,
        carbsGrams: 7,
        fatsGrams: 48,
      },
    ],
  },
  {
    id: 'diet_std_weightloss_04',
    tenantId: 'tenant_default',
    title: 'Standard Weight Loss & Fat Burn (1600 kcal)',
    isAdv: false,
    category: 'Weight Loss',
    targetGoal: 'Steady Healthy Fat Loss (0.5 - 1 kg / week)',
    dailyCalories: 1600,
    proteinGrams: 140,
    carbsGrams: 150,
    fatsGrams: 45,
    waterIntakeLiters: 3.5,
    description: 'Easy-to-follow balanced calorie deficit suitable for beginners and intermediate members aiming for sustainable fat loss.',
    supplements: ['Multivitamins', 'Whey Protein (1 Scoop)'],
    dosAndDonts: {
      dos: ['Eat fresh salad with every meal', 'Walk 8,000 to 10,000 steps daily'],
      donts: ['Do not drink sugary beverages or commercial juices'],
    },
    meals: [
      {
        id: 'm1',
        time: '08:00 AM',
        title: 'Breakfast - Healthy Eggs & Toast',
        foodItems: ['3 Egg Whites + 1 Whole Egg', '2 Slices Bran Bread', 'Green Tea'],
        calories: 320,
        proteinGrams: 22,
        carbsGrams: 28,
        fatsGrams: 8,
      },
      {
        id: 'm2',
        time: '01:30 PM',
        title: 'Lunch - Balanced Chicken Rice Plate',
        foodItems: ['150g Grilled Chicken', '1 Cup Boiled Rice', 'Fresh Cucumber & Tomato Salad'],
        calories: 480,
        proteinGrams: 40,
        carbsGrams: 50,
        fatsGrams: 8,
      },
      {
        id: 'm3',
        time: '05:00 PM',
        title: 'Evening Snack',
        foodItems: ['1 Apple or Guava', '10 Roasted Chana or Almonds'],
        calories: 180,
        proteinGrams: 6,
        carbsGrams: 24,
        fatsGrams: 5,
      },
      {
        id: 'm4',
        time: '08:00 PM',
        title: 'Dinner - Light Fish / Chicken Salad',
        foodItems: ['150g Steamed Fish or Chicken Tikka', 'Large Bowl Mixed Green Salad'],
        calories: 350,
        proteinGrams: 38,
        carbsGrams: 12,
        fatsGrams: 12,
      },
    ],
  },
  {
    id: 'diet_std_musclegain_05',
    tenantId: 'tenant_default',
    title: 'Standard Muscle Gain & Fitness Plan (2200 kcal)',
    isAdv: false,
    category: 'Muscle Gain',
    targetGoal: 'Lean Muscle Growth & Active Energy',
    dailyCalories: 2200,
    proteinGrams: 160,
    carbsGrams: 240,
    fatsGrams: 55,
    waterIntakeLiters: 3.5,
    description: 'Standard muscle building diet designed for active gym members seeking strength and healthy weight gain.',
    supplements: ['Whey Protein Shake', 'Creatine 3g'],
    dosAndDonts: {
      dos: ['Eat every 3 to 4 hours', 'Stay hydrated throughout gym workouts'],
      donts: ['Do not skip breakfast or post-workout meals'],
    },
    meals: [
      {
        id: 'm1',
        time: '08:00 AM',
        title: 'Breakfast',
        foodItems: ['2 Parathas cooked in light oil or 3 Slices Bread with 3 Eggs', '1 Glass Low Fat Milk'],
        calories: 520,
        proteinGrams: 28,
        carbsGrams: 62,
        fatsGrams: 16,
      },
      {
        id: 'm2',
        time: '01:30 PM',
        title: 'Lunch',
        foodItems: ['2 Roti (Whole Wheat)', '150g Chicken / Daal / Mutton Curry', 'Bowl of Yogurt & Salad'],
        calories: 580,
        proteinGrams: 42,
        carbsGrams: 68,
        fatsGrams: 14,
      },
      {
        id: 'm3',
        time: '05:30 PM',
        title: 'Pre/Post Workout',
        foodItems: ['1 Scoop Whey Protein', '2 Bananas', 'Handful of Nuts'],
        calories: 410,
        proteinGrams: 30,
        carbsGrams: 52,
        fatsGrams: 10,
      },
      {
        id: 'm4',
        time: '08:30 PM',
        title: 'Dinner',
        foodItems: ['150g Grilled Chicken Tikka or Fish', '1 Roti', 'Mixed Salad'],
        calories: 450,
        proteinGrams: 40,
        carbsGrams: 38,
        fatsGrams: 12,
      },
    ],
  },
];
