/**
 * Report Export Utility for SMG Manager
 * Supports CSV/Excel downloading and clean Printable HTML for PDF saving
 */

import { Member, PaymentRecord, Expense, AttendanceRecord, GymSettings } from '../types';

export function downloadCSV(filename: string, headers: string[], rows: (string | number)[][]) {
  const processRow = (row: (string | number)[]) =>
    row
      .map((val) => {
        const str = String(val ?? '');
        if (str.includes(',') || str.includes('"') || str.includes('\n')) {
          return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
      })
      .join(',');

  const csvContent = 'data:text/csv;charset=utf-8,\uFEFF' + [headers.join(','), ...rows.map(processRow)].join('\n');
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function printHTMLReport(title: string, settings: GymSettings, tableHeaders: string[], tableRows: (string | number)[][]) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate printable PDF report.');
    return;
  }

  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>${title} - ${settings.gymName}</title>
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          margin: 30px;
          color: #1f2937;
        }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-bottom: 2px solid #10b981;
          padding-bottom: 15px;
          margin-bottom: 20px;
        }
        .gym-name {
          font-size: 24px;
          font-weight: bold;
          color: #065f46;
        }
        .gym-sub {
          font-size: 13px;
          color: #6b7280;
        }
        .report-title {
          font-size: 18px;
          font-weight: 600;
          margin-bottom: 15px;
          color: #111827;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          font-size: 13px;
        }
        th, td {
          border: 1px solid #e5e7eb;
          padding: 8px 10px;
          text-align: left;
        }
        th {
          background-color: #f3f4f6;
          font-weight: 600;
          color: #374151;
        }
        tr:nth-child(even) {
          background-color: #f9fafb;
        }
        .footer {
          margin-top: 30px;
          font-size: 11px;
          color: #9ca3af;
          text-align: center;
          border-top: 1px solid #e5e7eb;
          padding-top: 10px;
        }
        @media print {
          body { margin: 15px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="gym-name">${settings.gymName}</div>
          <div class="gym-sub">${settings.address} | Contact: ${settings.adminMobile}</div>
        </div>
        <div style="text-align: right;">
          <div style="font-weight: bold; font-size: 14px;">${title}</div>
          <div class="gym-sub">Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}</div>
        </div>
      </div>

      <table border="1">
        <thead>
          <tr>
            ${tableHeaders.map((h) => `<th>${h}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${tableRows
            .map(
              (row) => `
            <tr>
              ${row.map((val) => `<td>${val ?? ''}</td>`).join('')}
            </tr>
          `
            )
            .join('')}
        </tbody>
      </table>

      <div class="footer">
        Generated by ${title} • Confidential Administration Report
      </div>

      <script>
        window.onload = function() {
          window.print();
        }
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}
